application: election-predictor
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /worker.*
  script: src.worker.app
  login: admin

- url: .*
  script: src.main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
